### PR TITLE
Python 3.x support & Windows filename issue

### PR DESCRIPTION
**Pull request by devil-tamachan**
Python 3.x support & Windows filename issue.

### CODE REVIEW

**Comment by devil-tamachan** [comment]
It was incomplete patch. I want you to reject it.

**Comment by devil-tamachan** [comment]
Patch has been completed. Please merge 5 commits together.

**Comment by strk** [comment]
Would be better to use separate PR for the separate issues (python 3 and windows)

**Comment by strk** [comment]
@devil-tamachan  can you do the split between the windows support and python3 one ?

**Comment by strk** [comment]
Closing due to lack of feedback

**Pull request closed without merging**
